language: python

python:
  - 2.7

install:
  - pip install codecov
  - pip install -r requirements.txt

script:
  - python tests/arithmetic_operators_test.py
  - coverage run tests/arithmetic_operators_test.py

after_success:
  - codecov